---

- name: Firewalls Fortinet rules
  hosts: fortinet
  connection: httpapi
  gather_facts: no
  tasks:
  - include_vars: ../../defaults/main.yml

  #https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/issues/186
  - name: Backup a Fortigate FW
    fortinet.fortios.fortios_monitor:
      vdom: "{{ fw_fg_vdom }}"
      access_token: "{{ fw_access_token }}"
      selector: 'backup.system.config'
      params:
        scope: 'vdom'
        #scope: 'global'
    register: backupinfo
  
  - name: Debug backup content
    debug:
      var: backupinfo

  - name: Save the backup information to a file
    copy:
      content: '{{ backupinfo.meta.raw }}'
      dest: "/tmp/local.backup"

- name: Store files via scp
  hosts: backup-server
  connection: ssh
  tasks:
  - include_vars: ../../defaults/main.yml

  - name: Create backup folder on backup server
    ansible.builtin.file:
      path: "{{ backup_server_folder }}"
      state: directory
    become: true

  - name: Copy config to backup server
    copy:
      src: "/tmp/local.backup"
      dest: "{{ backup_server_folder }}backup-fortinet-{{ '%Y-%m-%dT%H:%M:%S' | strftime(ansible_date_time.epoch) }}"
    become: true

  # https://ansible-galaxy-fortios-docs.readthedocs.io/en/galaxy-2.0.0/faq.html
  - name: Restore a Fortigate FW
    fortinet.fortios.fortios_monitor:
      vdom: "{{ fw_fg_vdom }}"
      access_token: "{{ fw_access_token }}"
      selector: 'restore.system.config'
      params:
        #scope: 'global'
        scope: 'vdom'
        source: 'upload'
        vdom: "{{ fw_fg_vdom }}"
        file_content: "{{ lookup( 'file', '/tmp/local.backup') | string | b64encode }}"
    become: true
    register: restoreinfo
