---

- name: Find Fortigate backup Files
  hosts: backup-server
  connection: ssh
  tasks:
  - include_vars: ../../defaults/main.yml

  - name: Find latest backup filename
    ansible.builtin.find:
      paths: "{{ backup_server_folder }}"
      file_type: file
      patterns: 'backup-fortinet*'
      # hidden: true
      use_regex: false
    become: yes
    register: backup_files

  - name: Get lastest backup ({{ (backup_files.files|last).path }})
    set_fact: 
      backup_file: "{{ (backup_files.files|last).path }}"

  - name: Fetch config from backup
    fetch:
      src: "{{ backup_file }}"
      dest: "/tmp/backup"
      flat: true
    when: backup_files | length > 0 
    register: tmp_backup_file


- name: Firewalls Fortinet rules
  hosts: fortinet
  connection: httpapi
  gather_facts: no
  tasks:
  - include_vars: ../../defaults/main.yml

  #https://ansible-galaxy-fortios-docs.readthedocs.io/en/galaxy-2.0.0/faq.html
  - name: Restore a Fortigate FW
    fortinet.fortios.fortios_monitor:
      vdom: "{{ fw_fg_vdom }}"
      access_token: "{{ fw_access_token }}"
      selector: 'restore.system.config'
      params:
        scope: 'global'
        source: 'upload'
        vdom: "{{ fw_fg_vdom }}"
        file_content: "{{ lookup( 'file', '/tmp/backup') | string | b64encode }}"
    register: backupinfo
  
  - name: Debug backup content
    debug:
      var: backupinfo
