---
#config system global
#  set rest-api enable
#end
- name: Firewalls Fortinet rules
  hosts: fortinet
  connection: httpapi
  gather_facts: no
  
  tasks:
  - include_vars: ../../defaults/main.yml
  
  - include_tasks: ../../tasks/fortinet/restore.yml
