---

- name: Firewalls Palo Alto rules
  hosts: panos
  connection: httpapi
  gather_facts: no
  
  tasks:
  - include_vars: ../../defaults/main.yml
  
  - include_tasks: ../../tasks/panos/rule_main.yml
