---

- name: Backup a Fortigate FW
  fortinet.fortios.fortios_monitor:
    vdom: "{{ fw_fg_vdom }}"
    access_token: "{{ fw_access_token }}"
    selector: 'backup.system.config'
    params:
      scope: 'global'
  register: backupinfo

- name: Save the backup information.
  copy:
    content: '{{ backupinfo.meta.raw }}'
    dest: '/tmp/backup'

  # - name: Create backup folder on backup server
  #   ansible.builtin.file:
  #     path: "{{ backup_server_folder }}"
  #     state: directory
  #   become: true
  #   delegate_to: "{{ backup_server }}"
  #   vars:
  #     ansible_user: "{{ backup_server_user }}"
  #     ansible_ssh_pass: "{{ backup_server_pass }}"

  # - name: Copy config to backup server
  #   copy:
  #     src: "{{ config.backup_path }}"
  #     dest: "{{ backup_server_folder }}{{ config.filename }}"
  #   become: true
  #   delegate_to: "{{ backup_server }}"
  #   vars:
  #     ansible_user: "{{ backup_server_user }}"
  #     ansible_ssh_pass: "{{ backup_server_pass }}"
