---

#  

# vars:
#     ansible_connection: httpapi
#     ansible_httpapi_use_ssl: yes
#     ansible_httpapi_validate_certs: no
#     ansible_httpapi_port: 443
    
- name: Gather facts from PanOS
  fortinet.fortios.fortios_configuration_fact:
    vdom: "root"
    #access_token: "{{ fw_access_token | default(omit) }}"
    selectors:
      - selector: "firewall_policy"
      - selector: "system_interface"
      - selector: "firewall_address"
  register: _fortinet_facts

- debug:
    var: _fortinet_facts