---
# main rule for Fortigate

- name: include 
  include_vars: ../../vars/fg_services.yml
  tags: [rule]

- name: Start loop for rules
  include_tasks:
    file: rule_loop.yml
    apply:
      tags: rule
  loop: "{{ fg_fw_rules }}"
  loop_control:
    label: "{{ _rule.name }}"
    loop_var: _rule
  when: fg_fw_rules | length > 0 
  tags: [rule]