---

- name: Query host objects
  check_point.mgmt.cp_mgmt_host_facts:
    #details_level: full
    details_level: standard
  register: _hosts
- name: Debug hosts
  debug:
    var: _hosts

- name: Query default access rule
  check_point.mgmt.cp_mgmt_access_rule_facts:
    #details_level: full
    details_level: standard
    layer: Network
    name: "Cleanup rule"
  register: _accessrules
  loop: "{{checkpoint_fw_rules}}"

- name: Query access rules
  check_point.mgmt.cp_mgmt_access_rule_facts:
    #details_level: full
    details_level: standard
    layer: Network
    name: "{{item.name}}"
  loop: "{{checkpoint_fw_rules}}"
  register: _accessrules
- name: Debug access rules
  debug:
    var: _accessrules

