---

- name: Query host objects
  check_point.mgmt.cp_mgmt_host_facts:
    details_level: full
    #details_level: standard
  ignore_errors: yes
  register: _hosts

- name: Query access rules
  check_point.mgmt.cp_mgmt_access_rule_facts:
    details_level: full
    #layer: "{{layer}}"
  ignore_errors: yes
  register: _accessrules

- name: Query default access rule
  check_point.mgmt.cp_mgmt_access_rule_facts:
    details_level: full
    #details_level: standard
    layer: "{{layer}}"
    name: "Cleanup rule"
  ignore_errors: yes
  register: _accessrules

- name: Query access rules
  check_point.mgmt.cp_mgmt_access_rule_facts:
    details_level: full
    #details_level: standard
    layer: "{{layer}}"
    name: "{{item.name}}"
  loop: "{{checkpoint_fw_rules}}"
  ignore_errors: yes
  register: _accessrules

# - name: Query network objects
#   check_point.mgmt.cp_mgmt_network_facts:
#     details_level: full
#     #details_level: standard
#   register: _networks

