---

- name: Create source hosts objects
  debug:
    msg: "{{item.1.name}},{{item.1.ipv4}}"
  with_subelements:
  - "{{checkpoint_fw_rules}}"
  - src.addresses

- name: Create destination hosts objects
  debug:
    msg: "{{item.1.name}},{{item.1.ipv4}}"
  with_subelements:
  - "{{checkpoint_fw_rules}}"
  - dest.addresses

- name: Create host object
  check_point.mgmt.cp_mgmt_host:
    name: "{{item.1.name}}"
    color: blue
    ip_address: "{{item.1.ipv4}}"
    ignore_warnings: true
    auto_publish_session: yes
  with_subelements:
  - "{{checkpoint_fw_rules}}"
  - src.addresses



# - name: Create access rule to deny access from host
#   check_point.mgmt.cp_mgmt_access_rule:
#     layer: "Network"
#     state: present
#     position: 1
#     name: "Deny traffic from 1.1.1.1 to 2.2.2.2"
#     source: "src-1.1.1.1"
#     destination: "dst-2.2.2.2"
# #    service: "{{item.service}}"
#     action: Drop
#     track:
#       type: log
#     auto_publish_session: yes

