---

- name: Create host object
  check_point.mgmt.cp_mgmt_host:
    name: "src-1.1.1.1"
    color: red
    ip_address: "1.1.1.1"
    ignore_warnings: true
    auto_publish_session: yes

- name: Create host object
  check_point.mgmt.cp_mgmt_host:
    name: "dst-2.2.2.2"
    color: blue
    ip_address: "2.2.2.2"
    ignore_warnings: true
    auto_publish_session: yes

- name: Create access rule to deny access from host
  check_point.mgmt.cp_mgmt_access_rule:
    layer: "Network"
    state: present
    position: 1
    name: "Deny traffic from from 1.1.1.1 to 2.2.2.2"
    source: "src-1.1.1.1"
    destination: "dst-2.2.2.2"
#    service: "{{item.service}}"
    action: Drop
    track:
      type: log
    auto_publish_session: yes
