---

- name: Create source hosts objects
  check_point.mgmt.cp_mgmt_host:
    name: "{{item.1.name}}"
    ip_address: "{{item.1.ipv4}}"
    ignore_warnings: true
    auto_publish_session: yes
  with_subelements:
  - "{{checkpoint_fw_rules}}"
  - src.addresses

- name: Create destination hosts objects
  check_point.mgmt.cp_mgmt_host:
    name: "{{item.1.name}}"
    ip_address: "{{item.1.ipv4}}"
    ignore_warnings: true
    auto_publish_session: yes
  with_subelements:
  - "{{checkpoint_fw_rules}}"
  - dest.addresses



- name: Create access rule
  check_point.mgmt.cp_mgmt_access_rule:
    layer: "Network"
    state: present
    position: 1
    name: "{{item.name}}"
    source: "{{item.src.addresses|map(attribute='name')|list}}"
    #- "pub_host_A"
    #- "pub_host_B"
    destination: "{{item.dest.addresses.name|map(attribute='name')|list}}"
    service: "{{item.services}}"
    action: Drop
    track:
      type: log
    auto_publish_session: yes
  loop: "{{checkpoint_fw_rules}}"

