---

- name: Gather Access Rules facts
  cisco.asa.asa_acls:
    state: gathered
  register: gather

- name: Debug 
  debug:
    var: gather | to_nice_yaml

- name: Manage Access Rules config
  cisco.asa.asa_acls:
    state: overridden
    config: "{{ asa_fw_rules }}"

