---

- name: Debug timestamp
  debug:
    var: ansible_date_time
  delegate_to: localhost

# git config --global user.email cparada@redhat.com
# git config --global user.name "Carlos Parada"
# git clone https://github.com/carlosfparada/ASA-SoT.git
# git branch today
# git checkout today
# git add .
# git commit -m "commit today"
# git push -u origin today
# Username: carlosfparada
# Password: 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

- name: Create a repo branch
  ansible.builtin.expect:
    command: "ssh -o StrictHostKeyChecking=no root@172.16.1.45"
    responses:
      # 'Are you sure you want to continue connecting (yes/no/[fingerprint])': "yes"
      # 'You are forced to change your password. Please input a new password.'
      's password:':
        - "Rfc1918!"
      '# ':
        - "mkdir /tmp/asa"
        - "cd /tmp/asa"
        - 'git config --global user.email cparada@redhat.com'
        - 'git config --global user.name "Carlos Parada"'
        - 'git clone https://github.com/carlosfparada/ASA-SoT.git'
        - 'cd ASA-SoT'
        - 'echo aa >> access-policies.yml'
        - "git branch today3"
        - "git checkout today3"
        - 'git add .'
        - 'git commit -m "commit today3"'
        - "git push -u origin today3"
        # - "rm -rf /tmp/asa"
        - 'exit'
      'Username':
        - 'carlosfparada'
      'Password':
        - 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
  no_log: false # hide passwords on logs
