---

- name: Git ASA SoT checkout
  ansible.builtin.git:
    repo: 'https://github.com/carlosfparada/ASA-SoT.git'
    dest: /tmp/asa/

- name: Set ASA SoT access rules
  set_fact:
    asa_sot: "{{ lookup('file','/tmp/asa/access-policies.yml') | from_yaml }}"

- name: Debug ASA SoT access rules
  debug:
    var: asa_sot

- name: Manage Access Rules config 2
  cisco.asa.asa_acls:
    state: overridden
    config: "{{ asa_sot2 }}"