---

- name: Gather Access Rules facts
  cisco.asa.asa_acls:
    state: gathered
  register: gather

- name: Debug 
  debug:
    var: gather.gathered | to_yaml

- name: Set Firewall access rules
  set_fact:
    asa_sot: "{{ gather.gathered }}"

- name: Manage Access Rules config
  cisco.asa.asa_acls:
    state: overridden
    config: "{{ asa_sot }}"

- name: Git checkout 2
  ansible.builtin.git:
    repo: 'https://github.com/carlosfparada/ASA-SoT.git'
    dest: /tmp/asa/

- name: Get Firewall access rules 2
  include_vars:
    file: "/tmp/asa/access-policies.yml"

- name: Debug ASA SoT content file 2
  debug:
    var: acls

- name: Manage Access Rules config 2
  cisco.asa.asa_acls:
    state: overridden
    config: "{{ acls }}"