---

# - name: Gather Access Rules facts
#   cisco.asa.asa_acls:
#     state: gathered
#   register: gather.gathered

# - name: Debug 
#   debug:
#     var: gather.gathered | to_nice_yaml

- name: Git checkout
  ansible.builtin.git:
    repo: 'https://github.com/carlosfparada/ASA-SoT.git'
    dest: /tmp/asa/

- name: Git checkout
  set_fact:
    asa_sot: "{{ lookup('file', '/tmp/asa/access-policies.yml') }}"

- name: Debug ASA SoT content file
  debug:
    var: asa_sot

- name: Manage Access Rules config
  cisco.asa.asa_acls:
    state: merged
    config: 
      acls: "{{ asa_sot }}"