---

- name: Configure interfaces
  cisco.asa.asa_config:
    lines:
    - "description {{item.description}}"
    - "nameif {{item.nameif}}"
    - "security-level {{item.security_level}}"
    - "ip address {{item.address|ipaddr('address')}} {{item.address|ipaddr('netmask')}}"
    - "no shutdown"
    parents: "interface {{item.name}}"
  loop: "{{interfaces}}"

- name: Configure traffic zones
  cisco.asa.asa_config:
    lines:
    - "zone {{item.name}}"
  loop: "{{zones}}"
  
- name: Configure traffic zones interfaces
  cisco.asa.asa_config:
    lines:
    - "zone-member {{item.0.name}}"
    parents: "interface {{item.1}}"
  with_subelements:
  - "{{zones}}"
  - interfaces




- name: Git ASA SoT checkout
  ansible.builtin.git:
    repo: 'https://github.com/carlosfparada/ASA-SoT.git'
    dest: /tmp/asa/

- name: Set ASA SoT access rules
  set_fact:
    asa_sot: "{{ lookup('file','/tmp/asa/access-policies.yml') | from_yaml }}"

- name: Debug ASA SoT access rules
  debug:
    var: asa_sot

- name: Manage ASA SoT access rules config
  cisco.asa.asa_acls:
    state: merged
    config: "{{ asa_sot }}"