---

- name: Debug timestamp
  debug:
    var: ansible_date_time.iso8601_basic

# git config --global user.email cparada@redhat.com
# git config --global user.name "Carlos Parada"
# git clone https://github.com/carlosfparada/ASA-SoT.git
# git branch today
# git checkout today
# git add .
# git commit -m "commit today"
# git push -u origin today
# Username: carlosfparada
# Password: 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

- name: Set admin initial password
  ansible.builtin.expect:
    command: "ssh -o StrictHostKeyChecking=no root@{{ 172.16.1.45 }}"
    responses:
      # 'Are you sure you want to continue connecting (yes/no/[fingerprint])': "yes"
      # 'You are forced to change your password. Please input a new password.'
      's password:':
      '# ':
        - "cd /tmp"
        - 'git config --global user.email cparada@redhat.com
        - 'git config --global user.name "Carlos Parada"
        - git clone https://github.com/carlosfparada/ASA-SoT.git
        - git branch today2
        - git checkout today2
        - git add .
        - git commit -m 'commit today2'
        - git push -u origin today2
        - exit
      'Username:':
        - carlosfparada
      'Password:':
        - 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

  no_log: false # hide passwords on logs
  ignore_errors: true

