---

- name: Gather Access Rules facts
  cisco.asa.asa_acls:
    state: gathered
  register: gather

- name: Debug 
  debug:
    var: gather | to_nice_yaml

- name: Git checkout
  ansible.builtin.git:
    repo: 'https://github.com/carlosfparada/ASA-SoT.git'
    dest: /tmp/asa-sot

- name: Git checkout
  set_fact:
    asa_sot: "{{ lookup('ansible.builtin.file', '/tmp/asa-sot/ASA-SoT/access-policies.yml') }}"

- name: Debug ASA SoT content file
  debug:
    var: asa_sot

- name: Manage Access Rules config
  cisco.asa.asa_acls:
    state: overridden
    config: 
      acls: "{{ asa_sot }}"