---

- name: Gather Access Rules facts
  cisco.asa.asa_acls:
    state: gathered
  register: gather

- name: Debug 
  debug:
    var: gather | to_nice_yaml

# - name: Manage Access Rules config
#   cisco.asa.asa_acls:
#     state: overridden
#     config: 
#       acls: "{{ asa_fw_rules }}"

- name: Git checkout
  ansible.builtin.git:
    repo: 'https://github.com/carlosfparada/ASA-SoT.git'
    dest: /tmp/asa-sot

