---

- name: Gather facts from Cisco ASA
  cisco.asa.asa_facts:
    # gather_network_resources:
    #   - all
    gather_subset: 
      - config
  register: _asa_facts

- name: Debug
  debug:
    var: _asa_facts

# New

- name: Gather facts from Cisco ASA (command)
  cisco.asa.asa_command:
    commands:
      - show
  register: _asa_facts