---

- name: Git ASA SoT checkout
  ansible.builtin.git:
    repo: 'https://github.com/carlosfparada/ASA-SoT.git'
    dest: /tmp/asa/

- name: Set ASA SoT access rules
  set_fact:
    asa_sot: "{{ lookup('file','/tmp/asa/access-policies.yml') | from_yaml }}"

- name: Debug ASA SoT access rules
  debug:
    var: asa_sot

- name: Manage ASA SoT access rules config
  cisco.asa.asa_acls:
    state: overridden
    config: "{{ asa_sot }}"
  #when: asa_sot is defined and asa_sot | length > 0

- name: Configure access rules
  cisco.asa.asa_config:
    src: ../../templates/asa/sot-rules.j2
  when: asa_sot is defined and asa_sot | length > 0
  register: result

- name: Debug access rules
  debug:
    var: result
