---

- name: Configure interfaces
  ansible.builtin.asa_config:
    lines:
    - "description {{item.description}}"
    - "nameif {{item.nameif}}"
    - "security-level {{item.security_level}}"
    - "ip address {{item.address|ipaddr('address')}} {{item.address|ipaddr('netmask')}}"
    - "no shutdown"
    parents: "interface {{item.name}}"
  loop: "{{interfaces}}"

- name: Configure traffic zones
  ansible.builtin.asa_config:
    lines:
    - "zone {{item.name}}"
  loop: "{{zones}}"
- name: Configure traffic zones interfaces
  ansible.builtin.asa_config:
    lines:
    - "zone-member {{item.0.name}}"
    parents: "interface {{item.1}}"
  with_subelements:
  - "{{zones}}"
  - interfaces



# hostname(config)# access-list OUTSIDE extended permit tcp host 10.1.1.14 host 209.165.200.225 eq www
# hostname(config)# access-list OUTSIDE extended permit tcp host 10.1.2.67 host 209.165.200.225 eq www
# hostname(config)# access-list OUTSIDE extended permit tcp host 10.1.3.34 host 209.165.200.225 eq www
# hostname(config)# access-group OUTSIDE out interface outside
#
# asa
# asa_fw_rules:
#   - name: rule_C
#     interface: "outside"
#     inout: in
#     src:
#       interface: "outside"
#       addresses:
#         - name: "inside_host_D"
#           ipv4: "10.10.2.3"
#     dest:
#       interface: "inside"
#       addresses:
#         - name: "pub_host_A"
#           type: host
#           ipv4: "7.7.7.1"
#         - name: "pub_host_B"
#           type: host
#           ipv4: "7.7.7.2"
#     services:
#       - http
#       - https
#     rule:
#       action: "permit"
#       #logging_init: false
#       #logging_close: true
#       #ips_sensor: "default"
#   - name: rule_D
#     interface: "outside"
#     inout: in
#     src:
#       interface: "outside"
#       addresses:
#         - name: "pub_host_E"
#           type: host
#           ipv4: "7.7.7.3"
#         - name: "pub_host_F"
#           type: host
#           ipv4: "7.7.7.4"
#     dest:
#       interface: "inside"
#       addresses:
#         - name: "inside_host_C"
#           ipv4: "10.10.2.4"
#     services:
#       - http
#       - https
#     rule:
#       action: "permit"
#       #logging_init: false
#       #logging_close: true
#       #ips_sensor: "default"