---

- name: Gather Access Rules facts
  cisco.asa.asa_acls:
    state: gathered
  register: gather

- name: Debug 
  debug:
    var: gather.gathered | to_yaml

- name: Create file with ASA SoT content
  ansible.builtin.copy:
    content: "{{ gather.gathered | to_yaml }}"
    dest: "/tmp/access-policies.yml"

- name: Set branch name
  set_fact:
    #branch_name: "{{ branch_name | default('branch') }}"
    branch_name: "branch-{{ '%Y%m%dT%H%M%S' | strftime }}"

- name: Create a repo branch
  ansible.builtin.expect:
    command: "su -"
    responses:
      '# ':
        - "mkdir /tmp/asa"
        - "cd /tmp/asa"
        - 'git config --global user.email cparada@redhat.com'
        - 'git config --global user.name "Carlos Parada"'
        - 'git clone https://github.com/carlosfparada/ASA-SoT.git'
        - 'cd ASA-SoT'
        - 'mv -f /tmp/access-policies.yml access-policies.yml'
        - "git branch \"{{ branch_name }}\""
        - "git checkout \"{{ branch_name }}\""
        - 'git add .'
        - "git commit -m \"commit {{ branch_name }}\""
        - "git push -u origin \"{{ branch_name }}\""
        - "rm -rf /tmp/asa"
        - 'exit'
      'Username':
        - 'carlosfparada'
      'Password':
        - "{{ authentication_token }}"
  no_log: false # hide passwords on logs