---

- name: Add address book entry line
  set_fact: 
    fw_conf_lines: "{{ fw_conf_lines + ['set security zones security-zone ' + item + ' address-book address ' + _address.name + ' ' + _address.ipv4] }}"
  loop: "{{ _zone }}"