---

- name: Backup config before deployment
  junipernetworks.junos.junos_config:
    backup: yes
    backup_options: 
      dir_path: "{{ fw_backup_dir }}"
  when: fw_backup_config | bool

- name: Change bulk config on JUNOS SRX 
  junipernetworks.junos.junos_config:
    lines: "{{ fw_conf_lines }}"
  register: _config

- name: Clear variable fw_config_lines
  set_fact:
    fw_conf_lines: []