---
# srx main.yml

- include_tasks: 
    file: facts.yml
    apply:
      tags: facts
  tags: [facts]

- include_tasks: rule_main_config.yml
  tags: [rule]

- include_tasks: rule_main_template.yml
  tags: [rule]