---
# # set security policies from-zone {{ security_policy.from }} to-zone {{ security_policy.to }} policy {{ security_policy.name }} match application {{ application }}

- name: set variable for policy services / applications
  set_fact:
    fw_conf_lines: "{{ fw_conf_lines + ['set security policies from-zone ' + item[0] + ' to-zone ' + item[1] + ' policy ' + _rule.name + ' match application ' + srx_services[_service] ] }}"
  with_nested: 
    - "{{ _src_zone }}"
    - "{{ _dest_zone }}"