---

- name: Firewalls ASA acls
  hosts: asa
  connection: network_cli
  gather_facts: no
  become: true
  
  tasks:
  - include_vars: ../../defaults/main.yml

  - include_tasks: ../../tasks/asa/rules-store-sot.yml