---

- name: Firewalls ASA rules
  hosts: asa
  connection: network_cli
  gather_facts: no
  become: true
  
  tasks:
  - include_vars: ../../defaults/main.yml

  - include_tasks: ../../tasks/asa/rules.yml

#  - include_tasks: ../../tasks/asa/rule_main.yml
