---

- name: Firewalls Juniper SRX - Template
  hosts: srx
  connection: local
  gather_facts: no

  tasks:
  - include_vars: ../../defaults/main.yml
  
  - include_tasks: ../../tasks/srx/rule_main_template.yml
