---

- name: Firewalls Juniper SRX - Config
  hosts: srx
  connection: local
  gather_facts: no
  vars:
    fw_methode_template: false
  tasks:
  - include_vars: ../../defaults/main.yml
  
  - include_tasks: ../../tasks/srx/rule_main.yml
