---

- name: Firewalls Checkpoint
  hosts: checkpoint
  connection: httpapi
  gather_facts: no
  become: true

  tasks:
  - include_vars: ../../defaults/main.yml
  
  - include_tasks: ../../tasks/checkpoint/main.yml
