---

- name: Firewalls Checkpoint rules
  hosts: checkpoint
  connection: httpapi
  gather_facts: no
  
  tasks:
  - include_vars: ../../defaults/main.yml

  - include_tasks: ../../tasks/checkpoint/rules.yml