---

- name: Gather facts from PanOS
  paloaltonetworks.panos.panos_facts:
    provider: "{{ panos_provider }}"
    gather_subset: 
      - "all" # all, system, session, interfaces, ha, routing, vr, vsys and config
  register: _panos_facts

- debug:
    var: _panos_facts