---
# main rule for PanOS

- name: Include 
  include_vars: ../../vars/panos_services.yml
  tags: [rule]

- name: Start loop for rules
  include_tasks:
    file: rule_loop.yml
    apply:
      tags: rule
  loop: "{{ fw_rules }}"
  loop_control:
    label: "{{ _rule.name }}"
    loop_var: _rule
  when: fw_rules | length > 0 
  tags: [rule]

- name: Commit configuration
  paloaltonetworks.panos.panos_commit_firewall:
    provider: "{{ panos_provider }}"
